filter:
    paths: [src/*]
    excluded_paths:
        - 'examples/*'
        - 'tests/*'
        - 'vendor/*'

tools:
    # Code Coverage
    external_code_coverage: true

checks:
    php: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true

build:
    environment:
        php:
            version: 7.3.0
