language: php

git:
    depth: 2

env:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
    - 7.3
    - 7.4
    - 8.0
    - nightly

install:
    - composer install --prefer-dist --no-interaction --optimize-autoloader --no-progress

script:
    - vendor/bin/php-cs-fixer fix --dry-run --diff
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
