language: php

## Run on container environment
sudo: false

env:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update

install:
    - composer install --prefer-dist

script:
    - vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php_cs
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
