language: php

## Run on container environment
sudo: false

## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

env:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
    - composer install --prefer-dist

script: phpunit
