language: php

## Run on container environment
sudo: false

## Cache composer
cache:
    directories:
        - $HOME/.composer/cache

env:
    - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

before_install:
    - composer self-update

install:
    - composer install --prefer-dist

script:
    - vendor/bin/phpcs --standard=PSR2 src/
    - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
